### ISSUE TITLE
To-Do

### ISSUE THREAD

**Issue by DongJu-Na** [DongJu-Na/sbwvss-mvc#4]
- [x] 동영상 ffmpeg으로 줄 수 있는 효과 확인. 
- [x] 템플릿 및 자막 적용 (미적 감각 필요 없음.) 
- [x] 큐알 코드 생성 후 동영상에 삽입. (랜딩url 넣어서)
